### ISSUE TITLE
能否支持投票类型的帖子

### ISSUE THREAD

**Issue by snecker** [kingwrcy/discussion#27]
社区论坛互动的话，投票是比较常见的，是否能支持

**Comment by kingwrcy** [comment]
会考虑添加的,后续补上.

**Comment by snecker** [comment]
搜索功能有在规划吗，大佬

**Comment by kingwrcy** [comment]
> 搜索功能有在规划吗，大佬

已经由[pull/39](https://github.com/kingwrcy/discussion/pull/39)实现了.
