### ISSUE TITLE
【需求】希望增加富文本优化和附件功能

### ISSUE THREAD

**Issue by ZAIDU-Miren** [kingwrcy/discussion#45]
--支持直接复制别站的文章内容，文本样式可以转换成[Markdown](https://www.markdownguide.org/)
图片支持自行配置图床地址，转换成图床地址
--支持附件（积分下载、浏览）

大佬你是最棒的

**Comment by kingwrcy** [comment]
附件就算了吧,还得管理文件,太复杂了,对不起这个名字 极简.
我看别的站v2,nodeseek 也不支持这些东西的.

**Comment by ZAIDU-Miren** [comment]
> 附件就算了吧，还得管理文件，太复杂了，对不起这个名字极简。 我看别的站v2，nodeseek 也不支持监管的。

不是，你理解错了，比如我放一个下载直链，扣除积分才给显示，都是指定文本内容，积分可以用来解锁一些资源

**Comment by kingwrcy** [comment]
那得考虑一个问题,这个链接如果被第一个人拿到了,直接把链接回复到帖子里,该怎么办?

**Comment by ZAIDU-Miren** [comment]
> 那得考虑一个问题,这个链接如果被第一个人拿到了,直接把链接回复到帖子里,该怎么办?

或者是帖子，通过积分扣除查看

**Comment by kingwrcy** [comment]
这个可以考虑,目前积分没有什么使用场景,这个算一个吧.
但是一般是很有价值的帖子才值得他人扣积分查看吧,还是那个问题,如果第一个看的人直接全文复制在评论里,如何处理呢?

**Comment by ZAIDU-Miren** [comment]
> 这个可以考虑,目前积分没有什么使用场景,这个算一个吧. 但是一般是很有价值的帖子才值得他人扣积分查看吧,还是那个问题,如果第一个看的人直接全文复制在评论里,如何处理呢?

任何一个阅读帖子，才能看到帖子中的评论啊，比如吾爱破解，帖子会根据等级，或者积分才有阅读权限，付费积分查看附件，一般也都是网盘地址，发评论这个确实没法阻止，但是第一个看的人确实是付费了的，就够了

**Comment by lateautumn2** [comment]
> > 附件就算了吧，还得管理文件，太复杂了，对不起这个名字极简。 我看别的站v2，nodeseek 也不支持监管的。
> 
> 不是，你理解错了，比如我放一个下载直链，扣除积分才给显示，都是指定文本内容，积分可以用来解锁一些资源

#48 已添加

**Comment by ZAIDU-Miren** [comment]
> > > 附件就算了吧，还得管理文件，太复杂了，对不起这个名字极简。 我看别的站v2，nodeseek 也不支持监管的。
> > 
> > 
> > 不是，你理解错了，比如我放一个下载直链，扣除积分才给显示，都是指定文本内容，积分可以用来解锁一些资源
> 
> #48 已添加

牛

**Comment by kingwrcy** [comment]
v1.1.8 已增加积分付费内容, 感谢 @lateautumn2 的pr.
