### ISSUE TITLE
【bug】首次登录注册没有提示

### ISSUE THREAD

**Issue by ZAIDU-Miren** [kingwrcy/discussion#46]
![recording](https://github.com/user-attachments/assets/9d658d2f-1ebd-46d6-87b5-dced59027137)

**Comment by kingwrcy** [comment]
不知道你这个是什么版本,我分别在本地和 discussion.mblog.club 上都试过了,注册完成之后会有提示,并且跳转到登录页面.
你这个一没有提示注册成功,二没有跳转登录,肯定是服务端报错导致的,还需要你看看到底服务端报错了什么?

**Comment by ZAIDU-Miren** [comment]
> 不知道你这个是什么版本,我分别在本地和 discussion.mblog.club 上都试过了,注册完成之后会有提示,并且跳转到登录页面. 你这个一没有提示注册成功,二没有跳转登录,肯定是服务端报错导致的,还需要你看看到底服务端报错了什么?

在服务器部署后，通过反代，进行IP+端口访问，看浏览器报错是ssl证书问题，websocke通信问题，大佬可以先忽视
