### ISSUE TITLE
add click back

### ISSUE THREAD

**Issue by lateautumn2** [kingwrcy/discussion#5]
有没有考虑在帖子详情页添加一键返回上一层级，参考nodeseek做法如下：
![image](https://github.com/kingwrcy/discussion/assets/57248164/c72e6e9a-f298-4828-b28c-76bd029e1dc0)

**Comment by kingwrcy** [comment]
下个版本添加上

**Comment by kingwrcy** [comment]
v1.0.4已添加了.
