### ISSUE TITLE
Add registration invitation code

### ISSUE THREAD

**Issue by lateautumn2** [kingwrcy/discussion#6]
大佬你好，考虑到数据库可能会被有心之人爆刷，在当前无邮箱验证的情况下（非必须），是否可添加 后台选择开启邀请码注册以及创建邀请码功能

**Comment by lateautumn2** [comment]
还有一个问题，大佬你的极简朋友圈和极简论坛打包的docker镜像，由于程序内部监听端口貌似都写死了3000，我修改了docker的监听端口3080:3000为3080:3080，会造成内部映射和实际监听对不上，项目无法访问

**Comment by kingwrcy** [comment]
冒号右边的端口不要改,只改左边,右边是固定的3000,左边才是你映射的端口.

邀请码是可以添加,一般论坛都会有这个功能.但是目前这个论坛刚起步,本来就没人玩,再加邀请码就凉了.

功能可以添加,目前不会开启.

**Comment by lateautumn2** [comment]
> 冒号右边的端口不要改,只改左边,右边是固定的3000,左边才是你映射的端口.
> 
> 邀请码是可以添加,一般论坛都会有这个功能.但是目前这个论坛刚起步,本来就没人玩,再加邀请码就凉了.
> 
> 功能可以添加,目前不会开启.

在docker里可以多个项目使用同一个监听接口吗，这个我不太了解，产生了误会，抱歉

**Comment by lateautumn2** [comment]
> 冒号右边的端口不要改,只改左边,右边是固定的3000,左边才是你映射的端口.
> 
> 邀请码是可以添加,一般论坛都会有这个功能.但是目前这个论坛刚起步,本来就没人玩,再加邀请码就凉了.
> 
> 功能可以添加,目前不会开启.

是的，我也是想到这点，所以邮箱验证完全没必要，但是想到注册可能会被爆刷，这个拦路虎还是必要的

**Comment by lateautumn2** [comment]
|O.O|，还有大佬有考虑 nodeseek的等级关联帖子权限这个功能吗

**Comment by kingwrcy** [comment]
我没明白你意思,现在有moments和discussion 2个应用,你如果使用docker启动的话,是2个单独的容器,moments可以监听容器的3000端口,discussion也可以监听容器的3000的端口.

这是2个独立的容器,端口不会冲突.冲突的的是docker映射到宿主机,就是冒号左边的端口,2个服务的映射到宿主机的端口不能一样,就不会冲突.

**Comment by lateautumn2** [comment]
> 我没明白你意思,现在有moments和discussion 2个应用,你如果使用docker启动的话,是2个单独的容器,moments可以监听容器的3000端口,discussion也可以监听容器的3000的端口.
> 
> 这是2个独立的容器,端口不会冲突.冲突的的是docker映射到宿主机,就是冒号左边的端口,2个服务的映射到宿主机的端口不能一样,就不会冲突.

第二个我的问题，我不太了解docker，我已经划掉了

**Comment by kingwrcy** [comment]
> |O.O|，还有大佬有考虑 nodeseek的等级关联帖子权限这个功能吗

这个也借鉴ns论坛的,也有留相关的接口了,只等人多点再实施,目前没意义,没几个注册用户.

**Comment by lateautumn2** [comment]
> > |O.O|，还有大佬有考虑 nodeseek的等级关联帖子权限这个功能吗
> 
> 这个也借鉴ns论坛的,也有留相关的接口了,只等人多点再实施,目前没意义,没几个注册用户.

这个确实，这个两个功能都是基于有用户而衍生的

**Comment by kingwrcy** [comment]
感谢你的打赏!这些功能有用户的情况下,都会支持的.
现在问题是如何吸引首批用户.

**Comment by lateautumn2** [comment]
我去几个论坛开贴~~宣传~~下moments和discussion

**Comment by lateautumn2** [comment]
定位确实是关键，去年的nodeseek，linux.do，一下子就起来了，但是做创造者社区，还是免不了~~要从v2拉人~~吸引v2的人，道阻且长啊
