### ISSUE TITLE
docker-compose 启动，注册的账号无法成功登陆，没有报错信息。登陆跳转后还是未登录状态。

### ISSUE THREAD

**Issue by tech1024** [kingwrcy/discussion#8]

**Comment by kingwrcy** [comment]
我这里测试了最新版的镜像,没有出现你说的问题.
如果你有问题,看下docker容器是否有报错?如果登录无法成功,看看登录时服务端返回了什么报错?

请提供详细的信息.

**Comment by kingwrcy** [comment]
问题找到了,你的站点不是https,之前的版本会设置cookie为secure,不支持非https站点.

v1.0.5已经默认cookie是非secure了,你重新拉取最新镜像即可.

如果要设置cookie为secure,可以配置环境变量,默认是false

```
NUXT_PUBLIC_COOKIE_SECURE=true
```

**Comment by tech1024** [comment]
谢谢提供解决方案，配置了https确实可用正常登录了。
